### ISSUE TITLE
OpenVPN Desktop Icon

### ISSUE THREAD

**Issue by JamesDynasty** [Thinstation/thinstation#631]
Is there any way to add a desktop icon for connecting to OpenVPN?

Like-wise, what's the best way to include the OpenVPN certificate files with the build image?

Thanks!

**Comment by Doncuppjr** [comment]
Have a look at https://github.com/Thinstation/thinstation/tree/6.2-Stable/ts/build/packages/openvpn/build/extra/etc/init.d
for some clues about how the openvpn package works. If you want a toggle, you could make a script, and add a /lib/menu/ file that will execute your script.

**Comment by JamesDynasty** [comment]
Hey @Doncuppjr,

Thanks for the direction! I was able to get a script in place to make the toggle and what-not.

Now my issue is when trying to connect to OpenVPN I get a permission error:
"Cannot ioctl TUNSETIFF tun: Operation not permitted (errno=1)"

How can I go about ensuring this has the appropriate permissions when running?

Thanks.

**Comment by Doncuppjr** [comment]
Try with an allmodules build. Might be some extra modules are needed.

**Comment by JamesDynasty** [comment]
Allmodules still gives the same error.

**Comment by JamesDynasty** [comment]
Using Ctrl+Alt+F2 and logging in as root allows me to connect as expected.

**Comment by Doncuppjr** [comment]
Could be a group thing. A regular user might not have perms to start a tunnel. You could possibly set up sudo to help out here.

**Comment by JamesDynasty** [comment]
I wasn't able to find any sort of guide on how to setup sudo in Thinstation. Do have somewhere for me to start with this?

Alternatively, would it be easier/possible to just give the tsuser full privileges?

Really appreciate all the help! Thanks again.

**Comment by Doncuppjr** [comment]
Sudo is not that wildly different than anywhere else. Include the sudo package, and include a sudoers.d file for the script that toggles openvpn.

You could just run as root everywhere of course, but people frown on that.

**Comment by JamesDynasty** [comment]
I realized I was in an outdated version of DevStation and decided to update before continuing. After updating my DevStation cannot see it's wifi card. I ended up reinstalling the version I had originally installed and it's still not detecting the card. I even installed windows and confirmed the card is working there, just not in my DevStation anymore. I know when I first installed it I didn't have to do anything, it just immediately popped up and prompted me to connect to wifi.

**Comment by Doncuppjr** [comment]
Interesting. Which network card do you have? output of ifconfig?

**Comment by JamesDynasty** [comment]
ifconfig doesn't show any wlan interfaces.

It's a laptop with an internal card: Realtek RTL8821CE 802.11b/g/n/ac

**Comment by Doncuppjr** [comment]
Something was wrong with the module. I think it's fixed now. Try updating DevStation.

**Comment by JamesDynasty** [comment]
Wifi is now working. Thanks! Hopefully now I can get my OpenVPN up and running properly.

**Comment by JamesDynasty** [comment]
Now it looks like the wifi on the actual thinstation build image isn't working. Made sure all wireless options are enabled and tried with allmodules.

Thanks.

**Comment by Thinstation** [comment]
I pushed fixed to git.

**Comment by JamesDynasty** [comment]
I updated the DevStation and rebuild the image, but I'm still facing the same issue. It didn't look like the DevStation actually updated.

**Comment by Thinstation** [comment]
It’s not the DevStation that needs to be updated now. The chroot needs a
factory reset

**Comment by JamesDynasty** [comment]
Gotcha! I factory reset and rebuilt out my configurations. I was able to add tsuser to the suoders for executing OpenVPN and my script works beautifully. Thanks for all your help!
